(in-package #:cl-chip8)
(defun display-reset! (machine)
  (dotimes (index (* +display-width+ +display-height+))
    (setf (row-major-aref (chip8-machine-framebuffer machine) index) 0))
  machine)
(defun display-pixel-value (machine x y) (check-type x (integer 0 63)) (check-type y (integer 0 31)) (aref (chip8-machine-framebuffer machine) y x))
(defun chip8-framebuffer-snapshot (machine)
  (let ((copy (make-array '(32 64) :element-type 'bit)))
    (dotimes (index (* +display-width+ +display-height+))
      (setf (row-major-aref copy index)
            (row-major-aref (chip8-machine-framebuffer machine) index)))
    copy))
(defun chip8-framebuffer (machine) (chip8-framebuffer-snapshot machine))
(defun display-xor-pixel! (machine x y)
  (let* ((fb (chip8-machine-framebuffer machine)) (old (aref fb y x))) (setf (aref fb y x) (logxor old 1)) (and (plusp old) (zerop (aref fb y x)))))
(defun chip8-clear-display! (machine) (display-reset! machine))
