(in-package #:cl-chip8)
(deftype display-framebuffer () 'chip8-framebuffer)
(deftype display-column () '(integer 0 63))
(deftype display-row () '(integer 0 31))
(deftype display-terminal-row () '(integer 0 15))
(deftype display-column-limit () '(integer 0 64))
(deftype display-row-limit () '(integer 0 32))
(deftype display-terminal-row-limit () '(integer 0 16))
(deftype display-row-bits () '(simple-array bit (64)))
