(in-package #:cl-chip8)
(defun chip8-run-instructions (machine count &key on-wait)
  (check-type count (integer 0 *))
  (let ((start (chip8-machine-instructions machine)) (done 0))
    (loop repeat count do (if (chip8-wait-state-kind (chip8-machine-waiting machine))
                              (progn (when on-wait (funcall on-wait machine)) (return))
                              (progn (execute-instruction! machine) (incf done)
                                     (when (chip8-wait-state-kind (chip8-machine-waiting machine)) (return)))))
    (make-chip8-run-result :status (if (chip8-wait-state-kind (chip8-machine-waiting machine)) :waiting :completed)
                           :executed (- (chip8-machine-instructions machine) start) :machine machine
                           :continuation (chip8-wait-state-continuation (chip8-machine-waiting machine)))))
(defun chip8-run-ticks (machine ticks &key (instructions-per-tick 1) on-wait)
  (dotimes (tick ticks)
    (step-timers! machine)
    (when (chip8-wait-state-kind (chip8-machine-waiting machine))
      (chip8-resume! machine :tick))
    (let ((result (chip8-run-instructions machine instructions-per-tick :on-wait on-wait)))
      (when (eq (chip8-run-result-status result) :waiting) (return result))))
  (make-chip8-run-result :status (if (chip8-wait-state-kind (chip8-machine-waiting machine)) :waiting :completed)
                         :executed (chip8-machine-instructions machine) :machine machine))
