(in-package #:cl-chip8)
(defparameter +keypad-mapping+ '((#\1 . 1) (#\2 . 2) (#\3 . 3) (#\4 . #xc) (#\q . 4) (#\w . 5) (#\e . 6) (#\r . #xd) (#\a . 7) (#\s . 8) (#\d . 9) (#\f . #xe) (#\z . #xa) (#\x . 0) (#\c . #xb) (#\v . #xf)))
(defun keypad-reset! (machine) (fill (chip8-machine-keypad machine) 0) machine)
(defun chip8-key-down! (machine key) (check-type key chip8-key) (setf (sbit (chip8-machine-keypad machine) key) 1) machine)
(defun chip8-key-up! (machine key) (check-type key chip8-key) (setf (sbit (chip8-machine-keypad machine) key) 0) machine)
(defun key-down-p (machine key) (plusp (sbit (chip8-machine-keypad machine) key)))
(defun pressed-keys (machine) (loop for key below 16 when (key-down-p machine key) collect key))
