(in-package #:cl-chip8)
(defun memory-reset! (machine) (fill (chip8-machine-memory machine) 0) (load-fontset-into-memory! machine) machine)
(defun check-memory-access (address span)
  (when (or (minusp address) (minusp span) (> (+ address span) +memory-size+))
    (error 'chip8-memory-access-out-of-bounds :address address :span span)) t)
(defun load-bytes-into-memory (machine bytes address)
  (check-memory-access address (length bytes))
  (when (or (minusp address) (> address +memory-size+) (> (length bytes) (- +memory-size+ address)))
    (error 'chip8-rom-too-large :size (length bytes) :available (- +memory-size+ address)))
  (replace (chip8-machine-memory machine) bytes :start1 address) machine)
(defun memory-read (machine address) (check-memory-access address 1) (aref (chip8-machine-memory machine) address))
(defun (setf memory-read) (value machine address) (check-memory-access address 1) (setf (aref (chip8-machine-memory machine) address) value))
