(in-package #:cl-chip8)
(define-condition chip8-cps-error (chip8-error) ((phase :initarg :phase :reader chip8-cps-error-phase) (cause :initarg :cause :reader chip8-cps-error-cause)))
(defun chip8-resume! (machine event)
  (let ((wait (chip8-machine-waiting machine)))
    (unless (chip8-wait-state-kind wait) (error 'chip8-cps-error :phase :resume :cause :not-waiting))
    (case (chip8-wait-state-kind wait)
      (:display (unless (eq event :tick) (return-from chip8-resume! machine)) (setf (chip8-machine-pc machine) (+ (chip8-wait-state-pc wait) 2)))
      (:key (destructuring-bind (kind key) event
              (when (and (integerp key) (or (eq kind :key-down) (eq kind :key-up)))
                (let ((complete (eq (chip8-quirks-fx0a-completion (chip8-machine-quirks machine)) :press)))
                  (when (or (and complete (eq kind :key-down)) (and (not complete) (eq kind :key-up)))
                    (setf (chip8-machine-register machine (chip8-wait-state-register wait)) key)
                    (setf (chip8-machine-pc machine) (+ (chip8-wait-state-pc wait) 2))))))))
    (when (and (not (eq (chip8-wait-state-kind wait) :key))
               (= (chip8-machine-pc machine) (+ (chip8-wait-state-pc wait) 2)))
      (setf (chip8-machine-waiting machine) (make-chip8-wait-state)))
    (when (and (eq (chip8-wait-state-kind wait) :key)
               (= (chip8-machine-pc machine) (+ (chip8-wait-state-pc wait) 2)))
      (setf (chip8-machine-waiting machine) (make-chip8-wait-state))) machine))
