(in-package #:cl-chip8)

(defun %skip-if (m condition) (advance-pc! m (if condition 4 2)))
(defun %vf-reset-if-needed (m) (when (eq (chip8-quirks-vf-behavior (chip8-machine-quirks m)) :reset) (setf (chip8-machine-register m 15) 0)))
(defun %execute-cls (m &rest ignored) (declare (ignore ignored)) (chip8-clear-display! m) (advance-pc! m))
(defun %execute-ret (m &rest ignored) (declare (ignore ignored)) (if (zerop (chip8-machine-sp m)) (error 'chip8-stack-underflow) (progn (decf (chip8-machine-sp m)) (setf (chip8-machine-pc m) (aref (chip8-machine-stack m) (chip8-machine-sp m))))))
(defun %execute-sys (m f x y n kk nnn) (declare (ignore f x y n kk nnn)) (advance-pc! m))
(defun %execute-jp (m f x y n kk nnn) (declare (ignore f x y n kk)) (setf (chip8-machine-pc m) nnn))
(defun %execute-call (m f x y n kk nnn) (declare (ignore f x y n kk)) (let ((sp (chip8-machine-sp m))) (when (>= sp +call-stack-limit+) (error 'chip8-stack-overflow :depth sp)) (setf (aref (chip8-machine-stack m) sp) (+ (chip8-machine-pc m) 2) (chip8-machine-sp m) (1+ sp) (chip8-machine-pc m) nnn)))
(defun %execute-se-byte (m f x y n kk nnn) (declare (ignore f y n nnn)) (%skip-if m (= (chip8-machine-register m x) kk)))
(defun %execute-sne-byte (m f x y n kk nnn) (declare (ignore f y n nnn)) (%skip-if m (/= (chip8-machine-register m x) kk)))
(defun %execute-se-register (m f x y n kk nnn) (declare (ignore f kk nnn)) (if (zerop n) (%skip-if m (= (chip8-machine-register m x) (chip8-machine-register m y))) (error 'chip8-invalid-opcode :opcode (logior #x5000 (ash x 8) (ash y 4) n))))
(defun %execute-ld-byte (m f x y n kk nnn) (declare (ignore f y n nnn)) (setf (chip8-machine-register m x) kk) (advance-pc! m))
(defun %execute-add-byte (m f x y n kk nnn) (declare (ignore f y n nnn)) (incf (chip8-machine-register m x) kk) (advance-pc! m))
(defun %execute-ld-register (m f x y n kk nnn) (declare (ignore f n kk nnn)) (setf (chip8-machine-register m x) (chip8-machine-register m y)) (advance-pc! m))
(defun %binary (m x y fn) (%vf-reset-if-needed m) (setf (chip8-machine-register m x) (funcall fn (chip8-machine-register m x) (chip8-machine-register m y))) (advance-pc! m))
(defun %execute-or (m f x y n kk nnn) (declare (ignore f n kk nnn)) (%binary m x y #'logior))
(defun %execute-and (m f x y n kk nnn) (declare (ignore f n kk nnn)) (%binary m x y #'logand))
(defun %execute-xor (m f x y n kk nnn) (declare (ignore f n kk nnn)) (%binary m x y #'logxor))
(defun %execute-add-register (m f x y n kk nnn) (declare (ignore f n kk nnn)) (let ((sum (+ (chip8-machine-register m x) (chip8-machine-register m y)))) (setf (chip8-machine-register m x) sum (chip8-machine-register m 15) (if (> sum 255) 1 0)) (advance-pc! m)))
(defun %execute-sub-register (m f x y n kk nnn) (declare (ignore f n kk nnn)) (let ((vx (chip8-machine-register m x)) (vy (chip8-machine-register m y))) (setf (chip8-machine-register m x) (- vx vy) (chip8-machine-register m 15) (if (>= vx vy) 1 0)) (advance-pc! m)))
(defun %execute-shr (m f x y n kk nnn) (declare (ignore f n kk nnn)) (let* ((vx (chip8-machine-register m x)) (vy (chip8-machine-register m y)) (source (if (eq (chip8-quirks-shift-source (chip8-machine-quirks m)) :vy) vy vx))) (setf (chip8-machine-register m 15) (logand source 1) (chip8-machine-register m x) (ash source -1)) (advance-pc! m)))
(defun %execute-subn-register (m f x y n kk nnn) (declare (ignore f n kk nnn)) (let ((vx (chip8-machine-register m x)) (vy (chip8-machine-register m y))) (setf (chip8-machine-register m x) (- vy vx) (chip8-machine-register m 15) (if (>= vy vx) 1 0)) (advance-pc! m)))
(defun %execute-shl (m f x y n kk nnn) (declare (ignore f n kk nnn)) (let* ((vx (chip8-machine-register m x)) (vy (chip8-machine-register m y)) (source (if (eq (chip8-quirks-shift-source (chip8-machine-quirks m)) :vy) vy vx))) (setf (chip8-machine-register m 15) (ldb (byte 1 7) source) (chip8-machine-register m x) (ash source 1)) (advance-pc! m)))
(defun %execute-sne-register (m f x y n kk nnn) (declare (ignore f kk nnn)) (if (zerop n) (%skip-if m (/= (chip8-machine-register m x) (chip8-machine-register m y))) (error 'chip8-invalid-opcode :opcode #x9001)))
(defun %execute-ld-i (m f x y n kk nnn) (declare (ignore f x y n kk)) (setf (chip8-machine-i m) nnn) (advance-pc! m))
(defun %execute-jp-v0 (m f x y n kk nnn) (declare (ignore f y n kk)) (let ((base (if (eq (chip8-quirks-bnnn-register (chip8-machine-quirks m)) :vx) (chip8-machine-register m x) (chip8-machine-register m 0)))) (setf (chip8-machine-pc m) (mod (+ nnn base) +memory-size+))))
(defun %execute-random (m f x y n kk nnn) (declare (ignore f y n nnn)) (setf (chip8-machine-register m x) (logand (random 256) kk)) (advance-pc! m))
(defun %execute-draw (m f x y n kk nnn)
  (declare (ignore f kk nnn))
  (let* ((q (chip8-machine-quirks m)) (i (chip8-machine-i m)) (vx (chip8-machine-register m x)) (vy (chip8-machine-register m y)) (collision nil))
    (check-memory-access i n)
    (dotimes (row n)
      (let ((byte (memory-read m (+ i row))))
        (dotimes (bit 8)
          (when (logbitp (- 7 bit) byte)
            (let ((px (+ (mod vx 64) bit)) (py (+ (mod vy 32) row)))
              (when (eq (chip8-quirks-clipping q) :wrap) (setf px (mod px 64) py (mod py 32)))
              (when (and (< px 64) (< py 32)) (when (display-xor-pixel! m px py) (setf collision t))))))))
    (setf (chip8-machine-register m 15) (if collision 1 0))
    (if (eq (chip8-quirks-display-wait q) :wait)
        (%install-display-wait! m)
        (advance-pc! m))))
(defun %execute-skip-key (m f x y n kk nnn) (declare (ignore f y n nnn)) (%skip-if m (if (= kk #x9e) (key-down-p m (chip8-machine-register m x)) (error 'chip8-invalid-opcode :opcode #xe000))))
(defun %execute-skip-not-key (m f x y n kk nnn) (declare (ignore f y n nnn)) (%skip-if m (if (= kk #xa1) (not (key-down-p m (chip8-machine-register m x))) (error 'chip8-invalid-opcode :opcode #xe000))))
(defun %execute-ld-delay (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (setf (chip8-machine-register m x) (chip8-machine-delay-timer m)) (advance-pc! m))
(defun %execute-wait-key (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (%execute-fx0a m x))
(defun %install-key-wait! (m x)
  (let ((pc (chip8-machine-pc m)))
    (setf (chip8-machine-waiting m)
          (make-chip8-wait-state
           :kind :key :pc pc :register x
           :continuation
           (lambda (event)
             (destructuring-bind (kind key) event
               (when (or (and (eq kind :key-down)
                              (eq (chip8-quirks-fx0a-completion
                                   (chip8-machine-quirks m)) :press))
                         (and (eq kind :key-up)
                              (eq (chip8-quirks-fx0a-completion
                                   (chip8-machine-quirks m)) :release)))
                 (setf (chip8-machine-register m x) key
                       (chip8-machine-pc m) (mod (+ pc 2) +memory-size+))
                 t)))))))

(defun %install-display-wait! (m)
  (let ((pc (chip8-machine-pc m)))
    (setf (chip8-machine-waiting m)
          (make-chip8-wait-state
           :kind :display :pc pc
           :continuation
           (lambda (event)
             (when (eq event :tick)
               (setf (chip8-machine-pc m) (mod (+ pc 2) +memory-size+))
               t))))))

(defun %execute-fx0a (m x)
  (let ((keys (pressed-keys m)))
    (if (and keys
             (eq (chip8-quirks-fx0a-completion (chip8-machine-quirks m)) :press))
        (progn
          (setf (chip8-machine-register m x) (first keys))
          (advance-pc! m))
        (%install-key-wait! m x))))
(defun %execute-ld-delay-from-vx (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (setf (chip8-machine-delay-timer m) (chip8-machine-register m x)) (advance-pc! m))
(defun %execute-ld-sound-from-vx (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (setf (chip8-machine-sound-timer m) (chip8-machine-register m x)) (advance-pc! m))
(defun %execute-add-i (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (%vf-reset-if-needed m) (setf (chip8-machine-i m) (ldb (byte 16 0) (+ (chip8-machine-i m) (chip8-machine-register m x)))) (advance-pc! m))
(defun %execute-ld-font (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (setf (chip8-machine-i m) (+ +fontset-address+ (* 5 (mod (chip8-machine-register m x) 16)))) (advance-pc! m))
(defun %execute-bcd (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (let ((v (chip8-machine-register m x)) (i (chip8-machine-i m))) (check-memory-access i 3) (setf (memory-read m i) (floor v 100) (memory-read m (1+ i)) (mod (floor v 10) 10) (memory-read m (+ i 2)) (mod v 10)) (advance-pc! m)))
(defun %store-registers! (m x) (let ((i (chip8-machine-i m))) (check-memory-access i (1+ x)) (dotimes (n (1+ x)) (setf (memory-read m (+ i n)) (chip8-machine-register m n))) (when (eq (chip8-quirks-memory-i (chip8-machine-quirks m)) :increment) (setf (chip8-machine-i m) (ldb (byte 16 0) (+ i x 1))))))
(defun %load-registers! (m x) (let ((i (chip8-machine-i m))) (check-memory-access i (1+ x)) (dotimes (n (1+ x)) (setf (chip8-machine-register m n) (memory-read m (+ i n)))) (when (eq (chip8-quirks-memory-i (chip8-machine-quirks m)) :increment) (setf (chip8-machine-i m) (ldb (byte 16 0) (+ i x 1))))))
(defun %execute-store-registers (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (%store-registers! m x) (advance-pc! m))
(defun %execute-load-registers (m f x y n kk nnn) (declare (ignore f y n kk nnn)) (%load-registers! m x) (advance-pc! m))
(defun execute-instruction! (machine)
  (when (chip8-wait-state-kind (chip8-machine-waiting machine)) (return-from execute-instruction! machine))
  (let* ((opcode (fetch-opcode machine)) (family (ldb (byte 4 12) opcode)) (x (opcode-x opcode)) (y (opcode-y opcode)) (n (opcode-n opcode)) (kk (opcode-kk opcode)) (nnn (opcode-nnn opcode)))
    (incf (chip8-machine-instructions machine))
    (dispatch-chip8-opcode machine opcode family x y n kk nnn))
  machine)

(define-chip8-dispatch)
