(in-package #:cl-chip8)
(defmacro define-chip8-opcode (name pattern mask fields &body body)
  `(defparameter ,(intern (format nil "+OPCODE-~A+" name) *package*)
     (list :name ',name :pattern ,pattern :mask ,mask :fields ',fields :body ',body)))
(defun opcode-x (opcode) (ldb (byte 4 8) opcode))
(defun opcode-y (opcode) (ldb (byte 4 4) opcode))
(defun opcode-n (opcode) (ldb (byte 4 0) opcode))
(defun opcode-kk (opcode) (ldb (byte 8 0) opcode))
(defun opcode-nnn (opcode) (ldb (byte 12 0) opcode))
