(in-package #:cl-chip8)
(defun %vf-reset-if-needed (machine)
  (when (eq (chip8-quirks-vf-behavior (chip8-machine-quirks machine)) :reset)
    (setf (chip8-machine-register machine 15) 0)))
(defun %skip-if (machine condition) (advance-pc! machine (if condition 4 2)))
(defun %draw-sprite! (machine x y n)
  (let* ((quirks (chip8-machine-quirks machine)) (i (chip8-machine-i machine))
         (vx (chip8-machine-register machine x)) (vy (chip8-machine-register machine y)) collision)
    (check-memory-access i n)
    (setf collision nil)
    (dotimes (row n)
      (let ((byte (memory-read machine (+ i row))))
        (dotimes (bit 8)
          (when (logbitp (- 7 bit) byte)
            (let ((px (+ (mod vx 64) bit)) (py (+ (mod vy 32) row)))
              (when (eq (chip8-quirks-clipping quirks) :wrap)
                (setf px (mod px 64) py (mod py 32)))
              (when (and (< px 64) (< py 32))
                (when (display-xor-pixel! machine px py) (setf collision t))))))))
    (setf (chip8-machine-register machine 15) (if collision 1 0))))
(defun %store-registers! (machine x)
  (let ((i (chip8-machine-i machine))) (check-memory-access i (1+ x))
    (dotimes (n (1+ x)) (setf (memory-read machine (+ i n)) (chip8-machine-register machine n)))
    (when (eq (chip8-quirks-memory-i (chip8-machine-quirks machine)) :increment)
      (setf (chip8-machine-i machine) (ldb (byte 16 0) (+ i x 1))))))
(defun %load-registers! (machine x)
  (let ((i (chip8-machine-i machine))) (check-memory-access i (1+ x))
    (dotimes (n (1+ x)) (setf (chip8-machine-register machine n) (memory-read machine (+ i n))))
    (when (eq (chip8-quirks-memory-i (chip8-machine-quirks machine)) :increment)
      (setf (chip8-machine-i machine) (ldb (byte 16 0) (+ i x 1))))))
(defun %execute-fx0a (machine x)
  (let ((keys (pressed-keys machine)))
    (if (and keys (eq (chip8-quirks-fx0a-completion (chip8-machine-quirks machine)) :press))
        (progn (setf (chip8-machine-register machine x) (first keys)) (advance-pc! machine))
        (setf (chip8-machine-waiting machine)
              (make-chip8-wait-state :kind :key :pc (chip8-machine-pc machine) :register x)))))
(defun execute-instruction! (machine)
  (when (chip8-wait-state-kind (chip8-machine-waiting machine)) (return-from execute-instruction! machine))
  (let* ((opcode (fetch-opcode machine)) (family (ldb (byte 4 12) opcode))
         (x (opcode-x opcode)) (y (opcode-y opcode)) (n (opcode-n opcode)) (kk (opcode-kk opcode)) (nnn (opcode-nnn opcode)))
    (incf (chip8-machine-instructions machine))
    (case family
      ((0) (cond
             ((= opcode #x00e0) (chip8-clear-display! machine) (advance-pc! machine))
             ((= opcode #x00ee)
              (if (zerop (chip8-machine-sp machine)) (error 'chip8-stack-underflow)
                  (progn (decf (chip8-machine-sp machine))
                         (setf (chip8-machine-pc machine)
                               (aref (chip8-machine-stack machine) (chip8-machine-sp machine))))))
             (t (advance-pc! machine))))
      ((1) (setf (chip8-machine-pc machine) nnn))
      ((2) (let ((sp (chip8-machine-sp machine))) (when (>= sp 16) (error 'chip8-stack-overflow :depth sp)) (setf (aref (chip8-machine-stack machine) sp) (+ (chip8-machine-pc machine) 2) (chip8-machine-sp machine) (1+ sp) (chip8-machine-pc machine) nnn)))
      ((3) (%skip-if machine (= (chip8-machine-register machine x) kk)))
      ((4) (%skip-if machine (/= (chip8-machine-register machine x) kk)))
      ((5) (if (zerop n) (%skip-if machine (= (chip8-machine-register machine x) (chip8-machine-register machine y))) (error 'chip8-invalid-opcode :opcode opcode)))
      ((6) (setf (chip8-machine-register machine x) kk) (advance-pc! machine))
      ((7) (incf (chip8-machine-register machine x) kk) (advance-pc! machine))
      ((8) (let ((vx (chip8-machine-register machine x)) (vy (chip8-machine-register machine y)))
           (case n
             ((0) (setf (chip8-machine-register machine x) vy))
             ((1) (%vf-reset-if-needed machine) (setf (chip8-machine-register machine x) (logior vx vy)))
             ((2) (%vf-reset-if-needed machine) (setf (chip8-machine-register machine x) (logand vx vy)))
             ((3) (%vf-reset-if-needed machine) (setf (chip8-machine-register machine x) (logxor vx vy)))
             ((4) (let ((sum (+ vx vy))) (setf (chip8-machine-register machine x) sum (chip8-machine-register machine 15) (if (> sum 255) 1 0))))
             ((5) (setf (chip8-machine-register machine x) (- vx vy) (chip8-machine-register machine 15) (if (>= vx vy) 1 0)))
             ((6) (let ((source (if (eq (chip8-quirks-shift-source (chip8-machine-quirks machine)) :vy) vy vx))) (setf (chip8-machine-register machine 15) (logand source 1) (chip8-machine-register machine x) (ash source -1))))
             ((7) (setf (chip8-machine-register machine x) (- vy vx) (chip8-machine-register machine 15) (if (>= vy vx) 1 0)))
             ((14) (let ((source (if (eq (chip8-quirks-shift-source (chip8-machine-quirks machine)) :vy) vy vx))) (setf (chip8-machine-register machine 15) (ldb (byte 1 7) source) (chip8-machine-register machine x) (ash source 1))))
             (t (error 'chip8-invalid-opcode :opcode opcode))) (advance-pc! machine)))
      ((9) (if (zerop n) (%skip-if machine (/= (chip8-machine-register machine x) (chip8-machine-register machine y))) (error 'chip8-invalid-opcode :opcode opcode)))
      ((10) (setf (chip8-machine-i machine) nnn) (advance-pc! machine))
      ((11) (let ((base (if (eq (chip8-quirks-bnnn-register (chip8-machine-quirks machine)) :vx) (chip8-machine-register machine x) (chip8-machine-register machine 0)))) (setf (chip8-machine-pc machine) (mod (+ nnn base) 4096))))
      ((12) (setf (chip8-machine-register machine x) (logand (random 256) kk)) (advance-pc! machine))
      ((13) (%draw-sprite! machine x y n) (if (eq (chip8-quirks-display-wait (chip8-machine-quirks machine)) :wait) (setf (chip8-machine-waiting machine) (make-chip8-wait-state :kind :display :pc (chip8-machine-pc machine))) (advance-pc! machine)))
      ((14) (%skip-if machine (if (= kk #x9e) (key-down-p machine (chip8-machine-register machine x)) (if (= kk #xa1) (not (key-down-p machine (chip8-machine-register machine x))) (error 'chip8-invalid-opcode :opcode opcode)))))
      ((15) (case kk
            ((7) (setf (chip8-machine-register machine x) (chip8-machine-delay-timer machine)) (advance-pc! machine))
            ((10) (%execute-fx0a machine x))
            ((21) (setf (chip8-machine-delay-timer machine) (chip8-machine-register machine x)) (advance-pc! machine))
            ((24) (setf (chip8-machine-sound-timer machine) (chip8-machine-register machine x)) (advance-pc! machine))
            ((30) (%vf-reset-if-needed machine) (setf (chip8-machine-i machine) (ldb (byte 16 0) (+ (chip8-machine-i machine) (chip8-machine-register machine x)))) (advance-pc! machine))
            ((41) (setf (chip8-machine-i machine) (+ +fontset-address+ (* 5 (mod (chip8-machine-register machine x) 16)))) (advance-pc! machine))
            ((51) (let ((v (chip8-machine-register machine x)) (i (chip8-machine-i machine))) (check-memory-access i 3) (setf (memory-read machine i) (floor v 100) (memory-read machine (1+ i)) (mod (floor v 10) 10) (memory-read machine (+ i 2)) (mod v 10)) (advance-pc! machine)))
            ((85) (%store-registers! machine x) (advance-pc! machine))
            ((101) (%load-registers! machine x) (advance-pc! machine))
            (t (error 'chip8-invalid-opcode :opcode opcode)))))
    machine))
