(in-package #:cl-chip8)

;;; The single source of truth for the 35 CHIP-8 instruction declarations.
(defvar *chip8-opcode-definitions* nil)

(defmacro define-chip8-opcode (name pattern mask fields handler &key quirks)
  `(progn
     (defparameter ,(intern (format nil "+OPCODE-~A+" name) *package*)
       (list :name ',name :pattern ,pattern :mask ,mask :fields ',fields
             :handler ',handler :quirks ',quirks))
     (pushnew ',(intern (format nil "+OPCODE-~A+" name) *package*)
              *chip8-opcode-definitions* :test #'eq)))

(define-chip8-opcode cls #x00e0 #xffff () %execute-cls)
(define-chip8-opcode ret #x00ee #xffff () %execute-ret)
(define-chip8-opcode sys #x0000 #xf000 (nnn) %execute-sys)
(define-chip8-opcode jp #x1000 #xf000 (nnn) %execute-jp)
(define-chip8-opcode call #x2000 #xf000 (nnn) %execute-call)
(define-chip8-opcode se-byte #x3000 #xf000 (x kk) %execute-se-byte)
(define-chip8-opcode sne-byte #x4000 #xf000 (x kk) %execute-sne-byte)
(define-chip8-opcode se-register #x5000 #xf00f (x y) %execute-se-register)
(define-chip8-opcode ld-byte #x6000 #xf000 (x kk) %execute-ld-byte)
(define-chip8-opcode add-byte #x7000 #xf000 (x kk) %execute-add-byte)
(define-chip8-opcode ld-register #x8000 #xf00f (x y) %execute-ld-register)
(define-chip8-opcode or #x8001 #xf00f (x y) %execute-or)
(define-chip8-opcode and #x8002 #xf00f (x y) %execute-and)
(define-chip8-opcode xor #x8003 #xf00f (x y) %execute-xor)
(define-chip8-opcode add-register #x8004 #xf00f (x y) %execute-add-register)
(define-chip8-opcode sub-register #x8005 #xf00f (x y) %execute-sub-register)
(define-chip8-opcode shr #x8006 #xf00f (x) %execute-shr :quirks (:shift-source))
(define-chip8-opcode subn-register #x8007 #xf00f (x y) %execute-subn-register)
(define-chip8-opcode shl #x800e #xf00f (x) %execute-shl :quirks (:shift-source))
(define-chip8-opcode sne-register #x9000 #xf00f (x y) %execute-sne-register)
(define-chip8-opcode ld-i #xa000 #xf000 (nnn) %execute-ld-i)
(define-chip8-opcode jp-v0 #xb000 #xf000 (nnn) %execute-jp-v0 :quirks (:bnnn-register))
(define-chip8-opcode random #xc000 #xf000 (x kk) %execute-random)
(define-chip8-opcode draw #xd000 #xf000 (x y n) %execute-draw :quirks (:display-wait :clipping))
(define-chip8-opcode skip-key #xe09e #xf0ff (x) %execute-skip-key)
(define-chip8-opcode skip-not-key #xe0a1 #xf0ff (x) %execute-skip-not-key)
(define-chip8-opcode ld-delay #xf007 #xf0ff (x) %execute-ld-delay)
(define-chip8-opcode wait-key #xf00a #xf0ff (x) %execute-wait-key :quirks (:fx0a-completion))
(define-chip8-opcode ld-delay-from-vx #xf015 #xf0ff (x) %execute-ld-delay-from-vx)
(define-chip8-opcode ld-sound-from-vx #xf018 #xf0ff (x) %execute-ld-sound-from-vx)
(define-chip8-opcode add-i #xf01e #xf0ff (x) %execute-add-i :quirks (:vf-behavior))
(define-chip8-opcode ld-font #xf029 #xf0ff (x) %execute-ld-font)
(define-chip8-opcode bcd #xf033 #xf0ff (x) %execute-bcd)
(define-chip8-opcode store-registers #xf055 #xf0ff (x) %execute-store-registers :quirks (:memory-i))
(define-chip8-opcode load-registers #xf065 #xf0ff (x) %execute-load-registers :quirks (:memory-i))

(defun opcode-x (opcode) (ldb (byte 4 8) opcode))
(defun opcode-y (opcode) (ldb (byte 4 4) opcode))
(defun opcode-n (opcode) (ldb (byte 4 0) opcode))
(defun opcode-kk (opcode) (ldb (byte 8 0) opcode))
(defun opcode-nnn (opcode) (ldb (byte 12 0) opcode))
