(in-package #:cl-user)
(defpackage #:cl-chip8
  (:use #:cl)
  (:import-from #:cl-tty-kit #:key-event-type #:key-event-code #:key-event-kind #:make-input-decoder #:decode-input #:decode-input-chunk #:make-renderer #:renderer-screen #:renderer-render #:renderer-resize #:screen-write-string #:with-screen-batch #:make-style #:with-raw-mode #:with-terminal-session #:tick-loop-run-realtime)
  (:import-from #:cl-cli #:make-app #:make-option #:make-positional #:run-app #:option-value #:positional-value #:current-process-argv)
  (:import-from #:cl-concurrent-kit #:make-executor #:shutdown-executor #:submit #:make-channel #:make-semaphore #:send #:try-send #:recv #:close-channel #:wait-on-semaphore #:signal-semaphore #:executor-queue-depth #:executor-high-water-mark #:make-atomic-counter #:atomic-counter-value #:atomic-counter-incf #:make-lock #:with-lock-held)
  (:import-from #:host-kit #:quit)
  (:export #:chip8-error #:chip8-rom-too-large #:chip8-rom-too-large-size #:chip8-rom-too-large-available #:chip8-rom-short-read #:chip8-rom-short-read-actual-size #:chip8-rom-short-read-expected-size #:chip8-invalid-opcode #:chip8-invalid-opcode-opcode #:chip8-stack-overflow #:chip8-stack-overflow-depth #:chip8-stack-underflow #:chip8-memory-access-out-of-bounds #:chip8-memory-access-out-of-bounds-address #:chip8-memory-access-out-of-bounds-span #:chip8-rom-not-regular-file #:chip8-rom-not-regular-file-path #:chip8-cps-error #:chip8-cps-error-phase #:chip8-cps-error-cause
   #:+memory-size+ #:+rom-load-address+ #:+register-count+ #:+initial-pc+ #:+call-stack-limit+ #:+display-width+ #:+display-height+ #:+fontset-address+ #:+chip8-fontset+
   #:chip8-machine #:chip8-machine-p #:make-chip8-machine #:chip8-reset! #:chip8-machine-memory #:chip8-machine-v #:chip8-machine-register #:chip8-machine-i #:chip8-machine-pc #:chip8-machine-sp #:chip8-machine-stack #:chip8-machine-delay-timer #:chip8-machine-sound-timer #:chip8-machine-keypad #:chip8-machine-framebuffer #:chip8-machine-quirks #:chip8-machine-waiting #:chip8-machine-instructions
   #:chip8-quirks #:chip8-quirks-p #:make-chip8-quirks #:merge-chip8-quirks #:chip8-quirks-profile #:chip8-quirks-vf-behavior #:chip8-quirks-memory-i #:chip8-quirks-display-wait #:chip8-quirks-clipping #:chip8-quirks-shift-source #:chip8-quirks-bnnn-register #:chip8-quirks-fx0a-completion
   #:memory-reset! #:load-bytes-into-memory #:check-memory-access #:memory-read #:load-fontset-into-memory! #:display-reset! #:display-pixel-value #:display-xor-pixel! #:chip8-framebuffer #:chip8-framebuffer-snapshot #:execute-instruction! #:fetch-opcode #:step-timers! #:sound-timer-active-p #:keypad-reset! #:key-down-p #:pressed-keys #:chip8-key-down! #:chip8-key-up! #:load-rom #:load-rom-file
   #:chip8-run-result #:chip8-run-result-status #:chip8-run-result-executed #:chip8-run-result-machine #:chip8-run-result-continuation #:chip8-run-instructions #:chip8-run-ticks #:chip8-resume! #:render-chip8! #:render-chip8-concurrently! #:run #:main #:image-entry-point))
