(in-package #:cl-chip8)
(defstruct (chip8-quirks (:constructor %make-chip8-quirks))
  (profile :modern :type (member :modern :cosmac-vip))
  (vf-behavior :preserve :type (member :preserve :reset))
  (memory-i :preserve :type (member :preserve :increment))
  (display-wait :none :type (member :none :wait)) (clipping :clip :type (member :clip :wrap))
  (shift-source :vx :type (member :vx :vy)) (bnnn-register :v0 :type (member :v0 :vx))
  (fx0a-completion :press :type (member :press :release)))
(defparameter *chip8-quirk-defaults*
  '((:modern . (:preserve :preserve :none :clip :vx :v0 :press))
    (:cosmac-vip . (:reset :increment :wait :wrap :vy :v0 :release))))
(defun make-chip8-quirks (&key (profile :modern) vf-behavior memory-i display-wait
                                clipping shift-source bnnn-register fx0a-completion)
  (let ((d (cdr (assoc profile *chip8-quirk-defaults*))))
    (unless d (error "Unknown CHIP-8 quirk profile: ~S" profile))
    (%make-chip8-quirks :profile profile :vf-behavior (or vf-behavior (first d))
                        :memory-i (or memory-i (second d)) :display-wait (or display-wait (third d))
                        :clipping (or clipping (fourth d)) :shift-source (or shift-source (fifth d))
                        :bnnn-register (or bnnn-register (sixth d))
                        :fx0a-completion (or fx0a-completion (seventh d)))))
(defun merge-chip8-quirks (quirks &rest overrides)
  (apply #'make-chip8-quirks (append (list :profile (chip8-quirks-profile quirks)) overrides)))
