(in-package #:cl-chip8)
(defun regular-file-p (path) (and (probe-file path) (sb-posix:s-isreg (sb-posix:stat-mode (sb-posix:stat (namestring path))))))
(defun load-rom (machine bytes &key (address +rom-load-address+)) (load-bytes-into-memory machine bytes address))
(defun load-rom-file (machine pathname)
  (when (and (probe-file pathname) (not (regular-file-p pathname))) (error 'chip8-rom-not-regular-file :path pathname))
  (with-open-file (stream pathname :element-type '(unsigned-byte 8))
    (let* ((size (file-length stream)) (bytes (make-array size :element-type '(unsigned-byte 8))))
      (read-sequence bytes stream) (load-rom machine bytes))))
