(in-package #:cl-chip8)
(defun step-timers! (machine)
  (when (plusp (chip8-machine-delay-timer machine)) (decf (chip8-machine-delay-timer machine)))
  (when (plusp (chip8-machine-sound-timer machine)) (decf (chip8-machine-sound-timer machine))) machine)
(defun sound-timer-active-p (&optional machine)
  (and machine (plusp (chip8-machine-sound-timer machine))))
