(in-package #:cl-chip8)
(defconstant +memory-size+ 4096)
(defconstant +rom-load-address+ #x200)
(defconstant +register-count+ 16)
(defconstant +initial-pc+ #x200)
(defconstant +call-stack-limit+ 16)
(defconstant +display-width+ 64)
(defconstant +display-height+ 32)
(defconstant +display-terminal-row-count+ 16)
(defconstant +fontset-address+ #x50)
(deftype chip8-octet () '(unsigned-byte 8))
(deftype chip8-nibble () '(unsigned-byte 4))
(deftype chip8-opcode () '(unsigned-byte 16))
(deftype chip8-key () '(unsigned-byte 4))
(deftype chip8-memory-index () '(integer 0 4095))
(deftype chip8-framebuffer () '(simple-array bit (32 64)))
(defstruct (chip8-wait-state (:constructor make-chip8-wait-state))
  (kind nil :type (member nil :key :display)) (pc 0 :type (unsigned-byte 16))
  (register 0 :type (unsigned-byte 4)) (continuation nil :type (or null function)))
(defstruct (chip8-run-result (:constructor make-chip8-run-result))
  (status :completed :type (member :completed :waiting :halted))
  (executed 0 :type (unsigned-byte 64)) machine continuation)
